# Configuration for welcome bot - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here!
  Your engagement is essential for open source projects, including Plone. :hugs:

  <br>If you haven't done so already,
  read [Plone's Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct).
  Also please follow the issue template, as it helps both you and other community members contribute more effectively.
  
  <br>If your issue is a feature request, others may raise its prominence through
  [feature voting](https://6.docs.plone.org/contributing/documentation/index.html#github-menu).

  <br>Welcome to the Plone community! :tada:

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for submitting your first pull request! You are awesome! :hugs:

  <br>If you haven't done so already, read
  [Plone's Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct)
  and [Contribute to documentation](https://6.docs.plone.org/contributing/documentation/index.html),
  as this will greatly help the review process.

  <br>Welcome to the EBP community! :tada:

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congratulations on your first merged pull request in this project! :tada:

  ![Congratulations](https://raw.githubusercontent.com/plone/documentation/fda4eadee4b0b71c4bcd0da739847444f74d3fc5/.github/images/congratulations.jpg)

  <br>Thank you for contributing, we are very proud of you! :heart:
